### ISSUE TITLE
Remove validate_against_schema option

### ISSUE THREAD

**Issue by bcb** [explodinglabs/jsonrpcclient#102]
There's no use for this feature. We should always validate.

Validating is fast, and only happens once.

**Comment by daeros** [comment]
Some sites don't use a valid schema, why should we be crippled from  working with them?

**Comment by bcb** [comment]
Fair point. (also made in #139)

But I guess if you want to work with servers giving invalid responses, you can use less of this library, something like this (for http):

```python
import requests
from jsonrpcclient.requests import Request

response = requests.post(endpoint, data=Request("ping"))
```

**Comment by bcb** [comment]
Closing in favour of #184
