### ISSUE TITLE
Support for symmetric jsonrpc

### ISSUE THREAD

**Issue by xim** [explodinglabs/jsonrpcclient#117]
We have a jsonrpc server that sends notifications to clients. I'd love it if it were possible to process incoming notifications on the client, e.g. by inheriting the client:

```
class MyClient(WebSocketsClient):
    def handle_notification(self, message):
        print(message['method'])
```

**Comment by bcb** [comment]
Probably wouldn't build this into the client, but I'm thinking you could do something like this, combining both jsonrpcclient and jsonrpcserver:

```python
import asyncio
import websockets
from jsonrpcclient.clients.websockets_client import WebSocketsClient
from jsonrpcserver import method, async_dispatch as dispatch

@method
async def ping():
    return "pong"

async def main(websocket, path):
    client = WebSocketsClient(websocket)
    while True:
        # Send
        response = await client.request("ping")
        print(response.data.result)
        # Receive
        response = await dispatch(await websocket.recv())
        if response.wanted:
            await websocket.send(str(response))

start_server = websockets.serve(main, "localhost", 5000)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by ZacharyACoon** [comment]
I was thinking a way to handle this is to map responses to request ids, and deque all the responses that weren't expected.
Then the user can add "handlers" that process the deque when unknown ids come in.

**Comment by bcb** [comment]
Won't be a problem in v4 https://github.com/explodinglabs/jsonrpcclient/discussions/171
