### ISSUE TITLE
rename request_id -> _request_id in requests.py#L140

### ISSUE THREAD

**Issue by IvanRyavkin** [explodinglabs/jsonrpcclient#138]
request_id is used very often in real life, now I have difficulties because I cannot pass the request_id parameter to get information about the request

if you agree to this issue, I'm willing to do it.

https://github.com/bcb/jsonrpcclient/blob/master/jsonrpcclient/requests.py#L140

**Comment by bcb** [comment]
Not sure I agree with the premise.

If this was to happen it’d be a breaking change and would have to go in the next major release.

**Comment by ashpooljh** [comment]
I'm having a similar problem with `Client.request()`. In my case, the RPC method itself [expects](https://docs.near.org/docs/api/rpc#call-a-contract-function) a `method_name` parameter. Specifying it via `**kwargs` makes it clash with the `method_name` argument used to determine the name of the RPC method.

It should be pointed out that any RPC parameter that also happens to be a [Python keyword](https://docs.python.org/3/reference/lexical_analysis.html#keywords) cannot be passed via `**kwargs` either.

As a generic solution to this kind of issue, I suggest adding an alternative way to pass RPC params other than via `*args` or `**kwargs`, e.g. by accepting a `dict`/`list` containing the params in a separate optional argument.

**Comment by bcb** [comment]
Yes good idea. 

> It should be pointed out that any RPC parameter that also happens to be a Python keyword cannot be passed via **kwargs either.

Is that true? What happens if you use a Python keyword?

**Comment by ashpooljh** [comment]
### Clash with a Python keyword
It's a syntax error:
```py
request("https://example.com", "test", for="loremipsum")
```
```
  File "<stdin>", line 1
    request("https://example.com", "test", for="loremipsum")
                                           ^
SyntaxError: invalid syntax
```
In BeautifulSoup, a popular library for parsing HTML, when it came to searching by CSS class they [had](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#searching-by-css-class) to use `class_` kwarg instead of `class` because of this.

This particular issue can be circumvented by using dict expansion.
```py
request("https://example.com", "test", **{"for": "loremipsum"})
```
This code raises an error too because example.com isn't really a jsonrpc server, but at least it sends the request successfully.
### Clash with a function argument
However, if one of the params has the same name as an argument used by the function, there's effectively no workaround. Both
```py
request("https://example.com", "test", **{"method_name": "loremipsum"})
```
and
```py
request("https://example.com", "test", method_name="loremipsum")
```
result in TypeError:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/jsonrpcclient/__init__.py", line 8, in request
    return HTTPClient(endpoint).request(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/apply_defaults/decorators.py", line 13, in wrapper
    return function(self, *args, **kwargs)
TypeError: request() got multiple values for argument 'method_name'
```

**Comment by bcb** [comment]
Ok we should add a way to pass a list or dict of arguments.

**Comment by ashpooljh** [comment]
Note that this too will be a breaking change in case a new function argument is introduced to pass the params. Whatever name we pick for this new argument, it will break existing code that uses that identifier as a name of an RPC parameter.

**Comment by bcb** [comment]
So in v4 I guess we should have a "params" parameter, like:
```python
>>> request("get", params=["foo"])
'{"jsonrpc": "2.0", "method": "get", "params": ["foo"], "id": 1}'
```
