### ISSUE TITLE
Two timeouts in AiohttpClient

### ISSUE THREAD

**Issue by Kaveshnikov** [explodinglabs/jsonrpcclient#142]
Hi! What is a purpose of async_timeout in [this block](https://github.com/bcb/jsonrpcclient/blob/master/jsonrpcclient/clients/aiohttp_client.py#L66)? Is this from time, when aiohttp didn't have one for read from the socket? I mean, there is a rather flexible timeout in aiohttp.ClientSession now, but because of default timeout in AiohttpClient `__init__()` I need to coordinate it with a ClientSession one. 

Summarizing the problem, when the ClientSession timeout is larger than AiohttpClient default one, AiohttpClient raises TimeoutError, which is unexpected. How about to add one interface for timeout setting for example in 4.x.x version?

**Comment by bcb** [comment]
Sounds good. I’d appreciatea pull requests since I’m not familiar with all these libraries.

It’s unfortunate this is a breaking change requiring a new major release. We really should consider moving the clients into their own packages.

**Comment by bcb** [comment]
Clients being removed from v4.

https://github.com/explodinglabs/jsonrpcclient/discussions/171
