### ISSUE TITLE
Anaconda package has wrong version dependency on click

### ISSUE THREAD

**Issue by bartdevriendt** [explodinglabs/jsonrpcclient#159]
The 3.3.6 version should have a click<8 dependency definition. But when trying to install jsonrpcclient from anaconda we get a conflict stating that click version should be <7.  If you check the index.json file in the package it indeed shows click<7 as dependency.  Maybe something went wrong with releasing to anaconda ?

**Comment by bcb** [comment]
Click is removed in v4
