### ISSUE TITLE
SimplyBook and Expecting value: line 1 column 1 (char 0) error

### ISSUE THREAD

**Issue by icfmp** [explodinglabs/jsonrpcclient#165]
Hi,

I sometimes receive the following error from SimplyBook.me : "Expecting value: line 1 column 1 (char 0)"

It seems SimplyBook.me sometimes respond non JSON content ...

How could I get the SimplyBook.me response to understand why I receive this non JSON response ?

Thanks.

**Comment by bcb** [comment]
It's a good point, you can't actually get access to the raw response if there's an error, this is a flaw in the jsonrpcclient library.

I would suggest sending the request yourself, using curl or requests, to see the response.

**Comment by bcb** [comment]
This won't be a problem in v4.
