### ISSUE TITLE
Log level should be customisable

### ISSUE THREAD

**Issue by maxenced** [explodinglabs/jsonrpcclient#168]
The default, hardcoded value of `info` for log should be lowered or parametrized to be customized. 
INFO is often used for printing meaningful information, while DEBUG is used for trace / dump etc. 

So i'd suggest to either switch to DEBUG or, better, make it configurable.

**Comment by bcb** [comment]
Yes, good point, those log entries probably should be on DEBUG.

I'm considering doing a new version of this after jsonrpcserver, and possibly remove the logging altogether as we've done with jsonrpcserver. Logging can be done by the user, outside of this library.

**Comment by bcb** [comment]
Logging will be removed in v4.
