### ISSUE TITLE
consider allowing overriding the standard json package with a different one (such as orjson)

### ISSUE THREAD

**Issue by jrobbins-LiveData** [explodinglabs/jsonrpcclient#195]
As an enhancement, it would be nice if we could specify the code providing `json.dumps` and `json.loads`. 

By way of an analogy, the `json-rpc` server package abstracts to `serialize` and `deserialize`  method.  See [here](https://github.com/pavlov99/json-rpc/blob/00b24a9e811d9ca89ec3b1570195c881687bbef4/jsonrpc/utils.py).

**Comment by bcb** [comment]
Hey Jeff,

The `request_json` function is simply `json.dumps` after `request`, and the `parse_json` function is simply `parse` after `json.loads`, so it should be trivial to write your own versions of these.

Actually this is a good candidate for the FAQ so I’ll add how to do this to the documentation when I get home in a few hours.

**Comment by jrobbins-LiveData** [comment]
Got it.  Agreed!

**Comment by bcb** [comment]
Added to FAQ https://www.jsonrpcclient.com/en/stable/faq.html
